# Generated by Django 4.2.5 on 2023-11-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('turbidity_value', models.FloatField()),
                ('turbidity_quality', models.CharField(max_length=20)),
                ('ph_value', models.FloatField()),
                ('ph_quality', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
            ],
        ),
    ]
