# Generated by Django 4.2.5 on 2023-11-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterdata',
            old_name='timestamp',
            new_name='datetime',
        ),
    ]
