# Generated by Django 4.2.5 on 2023-11-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterdata',
            name='water_tap',
            field=models.CharField(default='tap 1', max_length=20),
            preserve_default=False,
        ),
    ]
